name       : libavc1394
version    : 0.5.4
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libavc1394/libavc1394/libavc1394-0.5.4.tar.gz : 7cb1ff09506ae911ca9860bef4af08c2403f3e131f6c913a2cbd6ddca4215b53
license    : LGPL-2.1
summary    : Programming interface to the AV/C specification from the 1394 Trade Assocation.
description: |
    Programming interface to the AV/C specification from the 1394 Trade Assocation.
builddeps  :
    - pkgconfig(libraw1394)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
